Fix `useParamsWithFallback`
intuita-inc/cal.com-demo pull request #38
Opened 2023-10-12 14:08 UTC by hbjORbj

## What does this PR do?

- `Error: NextRouter was not mounted` is thrown if `useRouter` from `next/router` is called in App router. Since `useParamsWithFallback` is meant to be used in both page router and app router, this shouldn't happen. Simply wrapping `const router = useRouter()` inside try/catch clause resolves the issue.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Try to call the hook `useParamsWithFallback` in app router page. There is a sample app router page in the branch in this [PR](https://github.com/intuita-inc/cal.com-demo/pull/23)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-10-12 17:12 UTC, DmytroHryshyn approved these changes

2023-10-12 17:35 UTC, grzpab requested changes
Let's discuss it tomorrow.

2023-10-13 19:34 UTC, grzpab commented on packages/lib/hooks/useParamsWithFallback.ts
> +import { RouterContext } from "next/dist/shared/lib/router-context";
We need to explain why this change was needed (in a comment)

2023-10-13 19:34 UTC, grzpab commented on packages/lib/hooks/useParamsWithFallback.ts
> +export function useParamsWithFallback(): Params | ParsedUrlQuery | null {
you could get the retun type using TS inference, we can discuss that on Monday.
Also I think the return value is actually never nullable.

2023-10-13 19:34 UTC, grzpab commented on packages/features/ee/users/pages/users-edit-view.tsx
> +  const input = userIdSchema.safeParse(params) ?? {};
I am curious why was this change needed?

2023-10-13 19:34 UTC, grzpab commented on packages/features/ee/teams/pages/team-profile-view.tsx
> +  const teamId = Number(params?.id ?? "");
As mentioned in a separate comment, I think params always are a record object. We should handle the case when ID was not passed correctly, otherwise we get either 0 or NaN.

2023-10-16 13:46 UTC, hbjORbj commented on packages/lib/hooks/useParamsWithFallback.ts
> +export function useParamsWithFallback(): Params | ParsedUrlQuery | null {
Can you elaborate?

I got the types from nextjs repo:

`https://github.com/vercel/next.js/blob/canary/packages/next/src/shared/lib/router/router.ts#L358` and 
<img width="335" alt="Screenshot 2023-10-16 at 09 45 57" src="https://github.com/intuita-inc/cal.com-demo/assets/32841130/7d74dc12-7be8-443d-8922-8d3a63820482">

2023-10-16 13:47 UTC, hbjORbj commented on packages/features/ee/users/pages/users-edit-view.tsx
> +  const input = userIdSchema.safeParse(params) ?? {};
good catch! it's actually needless in this case.

2023-10-16 13:54 UTC, hbjORbj commented on packages/features/ee/teams/pages/team-profile-view.tsx
> +  const teamId = Number(params?.id ?? "");
`useParamsWithFallback` hook now returns `Params` or ParsedQuery` only and hence I could revert changes like this line above.

2023-10-23 12:58 UTC, grzpab commented on packages/lib/hooks/useParamsWithFallback.ts
> +    return params ?? {};
`?? {}` should no longer be needed here

2023-11-03 16:06 UTC, hbjORbj commented
closing this because I already opened a PR against cal repo

2023-11-03 16:06 UTC, closed without merging